import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';
import { SiteContent, defaultContent } from '../data/siteContent';

interface EditContextType {
    isEditMode: boolean;
    toggleEditMode: () => void;
    content: SiteContent;
    updateContent: <K extends keyof SiteContent>(
        section: K,
        data: SiteContent[K]
    ) => void;
    updateField: (path: string, value: string) => void;
    exportContent: () => void;
    hasChanges: boolean;
    resetChanges: () => void;
}

const EditContext = createContext<EditContextType | undefined>(undefined);

const STORAGE_KEY = 'portfolio-cms-content';

// Deep get value by path like "personal.name"
const getByPath = (obj: any, path: string): any => {
    return path.split('.').reduce((acc, key) => acc?.[key], obj);
};

// Deep set value by path
const setByPath = (obj: any, path: string, value: any): any => {
    const keys = path.split('.');
    const result = JSON.parse(JSON.stringify(obj));
    let current = result;

    for (let i = 0; i < keys.length - 1; i++) {
        current = current[keys[i]];
    }
    current[keys[keys.length - 1]] = value;

    return result;
};

export const EditModeProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [isEditMode, setIsEditMode] = useState(false);
    const [hasChanges, setHasChanges] = useState(false);

    // Load saved content or use defaults
    const [content, setContent] = useState<SiteContent>(() => {
        try {
            const saved = localStorage.getItem(STORAGE_KEY);
            if (saved) {
                setHasChanges(true);
                return JSON.parse(saved);
            }
        } catch (e) {
            console.error('Failed to load saved content:', e);
        }
        return defaultContent;
    });

    const toggleEditMode = useCallback(() => {
        setIsEditMode(prev => !prev);
    }, []);

    const updateContent = useCallback(<K extends keyof SiteContent>(
        section: K,
        data: SiteContent[K]
    ) => {
        setContent(prev => {
            const updated = { ...prev, [section]: data };
            localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
            setHasChanges(true);
            return updated;
        });
    }, []);

    const updateField = useCallback((path: string, value: string) => {
        setContent(prev => {
            const updated = setByPath(prev, path, value);
            localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
            setHasChanges(true);
            return updated;
        });
    }, []);

    const exportContent = useCallback(() => {
        const dataStr = JSON.stringify(content, null, 2);
        const blob = new Blob([
            `// Generated by CMS - Copy to src/data/siteContent.ts\n` +
            `import { SiteContent } from './siteContent';\n\n` +
            `export const defaultContent: SiteContent = ${dataStr};\n`
        ], { type: 'text/typescript' });

        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = 'siteContent.ts';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }, [content]);

    const resetChanges = useCallback(() => {
        localStorage.removeItem(STORAGE_KEY);
        setContent(defaultContent);
        setHasChanges(false);
    }, []);

    return (
        <EditContext.Provider value={{
            isEditMode,
            toggleEditMode,
            content,
            updateContent,
            updateField,
            exportContent,
            hasChanges,
            resetChanges
        }}>
            {children}
        </EditContext.Provider>
    );
};

export const useEditMode = (): EditContextType => {
    const context = useContext(EditContext);
    if (!context) {
        throw new Error('useEditMode must be used within EditModeProvider');
    }
    return context;
};

// Helper hook to get field value
export const useContentField = (path: string): string => {
    const { content } = useEditMode();
    return getByPath(content, path) ?? '';
};
